version: '3.9'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=message_repository
      - MYSQL_USER=tetiana
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
